name: LintR-check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lintr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install lintr
        run: Rscript -e 'renv::restore(prompt = FALSE)'

      - name: Install package
        run: Rscript -e 'install.packages(".", repos = NULL, type = "source")'

      - name: Run lintr
        shell: Rscript {0}
        run: |
          lints <- lintr::lint_package()
          for (lint in lints) print(lint)
          quit(status = length(lints) > 0)
