name: Spell-check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  spell:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install spelling package
        run: Rscript -e 'install.packages("spelling")'

      - name: Run spell check
        run: Rscript -e 'spelling::spell_check_package()'
