name: R-CMD-check + Test Coverage

on:
  push:
    branches: [main, master]
  pull_request:

jobs:
  test-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      - name: Setup dependencies
        uses: r-lib/actions/setup-renv@v2

      - name: Install testthat/covr
        run: Rscript -e 'install.packages(c("testthat", "covr"))'

      - name: Run tests
        run: Rscript -e 'devtools::test()'

      - name: Show Coverage
        run: Rscript -e 'covr::package_coverage()'

      - name: Run coverage and upload to Codecov
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: |
          Rscript -e 'covr::codecov()'
